{{- $pdb := .Values.podDisruptionBudget }}
{{- if or $pdb.minAvailable $pdb.maxUnavailable }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appName }}-pdb
spec:
  {{- if $pdb.minAvailable }}
  minAvailable: {{ $pdb.minAvailable }}
  {{- else if $pdb.maxUnavailable }}
  maxUnavailable: {{ $pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{ include "fluxsend.selectorLabels" . | nindent 6 }}
{{- end }}