# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "fluxsend.labels" . | nindent 4 }}
spec:
  selector:
    {{ include "fluxsend.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: backend
      protocol: TCP
      port: 3001
    - name: frontend
      protocol: TCP
      port: 8000
    - name: api
      protocol: TCP
      port: 8091
    - name: docs
      protocol: TCP
      port: 80